version: '3.9'

services:
  manager:
    image: jc21/nginx-proxy-manager:2.9.18
    environment:
      TZ: 'Europe/Paris'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.hostname == almanzo.lgdweb.ovh
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - /srv/nginx-proxy-manager/data:/data
      - /srv/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - internal
      - reverse-proxy-nw

networks:
  internal:
    driver: overlay
    attachable: true
  reverse-proxy-nw:
    external: true
