version: '3.9'

services:
  manager:
    image: jc21/nginx-proxy-manager:2.9.18
    environment:
      - 'DISABLE_IPV6=true'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.managerStatus == leader
    ports:
      - '80:80'
      - '443:443'
      # - '81:81'
    volumes:
      - /srv/nginx-proxy-manager/data:/data
      - /srv/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    networks:
      - reverse-proxy-nw
  alice:
    image: containous/whoami:latest
    ports:
      - 8881:80
    deploy:
      placement:
        constraints: [node.hostname == alice.lgdweb.ovh]
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - reverse-proxy-nw
  almanzo:
    image: containous/whoami:latest
    ports:
      - 8882:80
    deploy:
      placement:
        constraints: [node.hostname == almanzo.lgdweb.ovh]
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - reverse-proxy-nw
  laura:
    image: containous/whoami:latest
    ports:
      - 8883:80
    deploy:
      placement:
        constraints: [node.hostname == laura.lgdweb.ovh]
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - reverse-proxy-nw
  mary:
    image: containous/whoami:latest
    ports:
      - 8884:80
    deploy:
      placement:
        constraints: [node.hostname == mary.lgdweb.ovh]
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - reverse-proxy-nw
  nelson:
    image: containous/whoami:latest
    ports:
      - 8885:80
    deploy:
      placement:
        constraints: [node.hostname == nelson.lgdweb.ovh]
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - reverse-proxy-nw

networks:
  reverse-proxy-nw:
    external: true
