version: '3.9'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    environment:
      - 'DEFAULT_HOST=laura.lgdweb.ovh'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhosts:/etc/nginx/vhost.d
      - /var/log/nginx:/var/log/nginx
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    # labels:
    #   - 'com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy'

volumes:
  acme:
  certs:
  html:
  vhosts:
