version: '3.9'

services:
  agent:
    image: portainer/agent:2.14.2
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-nw
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  server:
    image: portainer/portainer-ce:2.14.2
    ports:
      - '9443:9443'
      - '9000:9000'
      - '8000:8000'
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - /srv/portainer-stack/data:/data
    networks:
      - agent-nw
      - reverse-proxy-nw
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.hostname == almanzo.lgdweb.ovh

networks:
  agent-nw:
    attachable: true
  reverse-proxy-nw:
    external: true
