version: '3.9'

services:
  snippet-box:
    image: pawelmalak/snippet-box:latest
    volumes:
      - /srv/tools-stack/snippet-box:/app/data
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - 5000:5000
    networks:
      - reverse-proxy-nw
  flame:
    image: pawelmalak/flame
    environment:
      PASSWORD: ${FLAME_PASSWORD}
    volumes:
      - /srv/tools-stack/flame:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    ports:
      - 5005:5005
    networks:
      - reverse-proxy-nw

networks:
  reverse-proxy-nw:
    external: true
