version: '3.8'

services:
  hbbs:
    container_name: 'rustdesk-id-${HOSTNAME}'
    image: rustdesk/rustdesk-server:latest
    ports:
      - 21115:21115
      - 21116:21116
      - 21116:21116/udp
      - 21118:21118
    volumes:
      - data:/root
    command: 'hbbs -r rustdesk.${HOSTNAME}.lgdweb.ovh:21117'
    networks:
      - rustdesk-nw
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: 'rustdesk-relay-${HOSTNAME}'
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    ports:
      - 21117:21117
      - 21119:21119
    volumes:
      - data:/root
    networks:
      - rustdesk-nw
    restart: unless-stopped

volumes:
  data:

networks:
  rustdesk-nw:
    external: false
