version: '3.8'

services:
  portainer-agent:
    container_name: 'portainer-agent-${HOSTNAME}'
    image: 'portainer/agent:2.20.2-alpine'
    ports:
      - '9001:9001'
    volumes:
      - '/:/host'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    # Uncomment the following line to enable the agent secret
    # environment:
    #   AGENT_SECRET: $AGENT_SECRET
    networks:
      - reverse-proxy-nw
    restart: unless-stopped

  # Uncomment the following block to enable the Portainer server, ideally only on one server
  # portainer-server:
  #   container_name: 'portainer-server-${HOSTNAME}'
  #   image: 'portainer/portainer-ce:2.20.2-alpine'
  #   # Uncomment the following line to enable the agent secret
  #   environment:
  #     AGENT_SECRET: $AGENT_SECRET
  #     TZ: 'Europe/Paris'
  #   ports:
  #     - '9443:9443'
  #     - '8000:8000'
  #   volumes:
  #     - '/var/run/docker.sock:/var/run/docker.sock'
  #     - '/srv/portainer/data:/data'
  #     - '/etc/localtime:/etc/localtime:ro'
  #     - '/etc/timezone:/etc/timezone:ro'
  #   networks:
  #     - reverse-proxy-nw
  #   restart: unless-stopped

networks:
  reverse-proxy-nw:
    external: true
